//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Messi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApiCache
    {
        public int ApiCacheId { get; set; }
        public string Word { get; set; }
        public string ImageUrl { get; set; }
        public string Definition { get; set; }
    }
}
