//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Messi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Game
    {
        public Game()
        {
            this.Rounds = new HashSet<Round>();
            this.UserPoints = new HashSet<UserPoint>();
        }
    
        public int GameId { get; set; }
        public int StatusId { get; set; }
        public string Word { get; set; }
        public string ImageUrl1 { get; set; }
        public string ImageUrl2 { get; set; }
        public string ImageUrl3 { get; set; }
        public string ImageUrl4 { get; set; }
        public string SelectedImageUrl { get; set; }
    
        public virtual ICollection<Round> Rounds { get; set; }
        public virtual ICollection<UserPoint> UserPoints { get; set; }
    }
}
