//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Messi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Round
    {
        public int RoundId { get; set; }
        public int GameId { get; set; }
        public int RoundNum { get; set; }
        public int UserId { get; set; }
        public string RecognizedText { get; set; }
    
        public virtual Game Game { get; set; }
        public virtual User User { get; set; }
    }
}
