//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Messi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Rounds = new HashSet<Round>();
            this.UserPoints = new HashSet<UserPoint>();
        }
    
        public int UserId { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string DisplayName { get; set; }
        public string CountryName { get; set; }
    
        public virtual ICollection<Round> Rounds { get; set; }
        public virtual ICollection<UserPoint> UserPoints { get; set; }
    }
}
